# Generated by Django 4.1.5 on 2023-08-28 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_details', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Commands',
            new_name='Comments',
        ),
    ]
